export const CASE_STATUSES = [
  "DRAFT",
  "REQUEST_READY",
  "WAITING_FOR_DOCUMENT",
  "DOCUMENT_RECEIVED",
  "PROCESSING",
  "NON_COMPLIANT",
  "WAITING_FOR_CORRECTION",
  "UNDER_REVIEW",
  "COMPLIANT",
  "CLEARED",
  "BLOCKED",
  "HUMAN_REVIEW",
  "CLOSED",
] as const;

export type CaseStatus = (typeof CASE_STATUSES)[number];
export type CaseType = "INITIAL" | "RENEWAL";

export const CASE_STATUS_TRANSITIONS: Record<
  CaseStatus,
  readonly CaseStatus[]
> = {
  DRAFT: ["REQUEST_READY", "DOCUMENT_RECEIVED", "CLOSED"],
  REQUEST_READY: ["WAITING_FOR_DOCUMENT", "DOCUMENT_RECEIVED", "CLOSED"],
  WAITING_FOR_DOCUMENT: [
    "DOCUMENT_RECEIVED",
    "BLOCKED",
    "HUMAN_REVIEW",
    "CLOSED",
  ],
  DOCUMENT_RECEIVED: ["PROCESSING", "HUMAN_REVIEW", "CLOSED"],
  PROCESSING: [
    "COMPLIANT",
    "NON_COMPLIANT",
    "UNDER_REVIEW",
    "HUMAN_REVIEW",
    "CLOSED",
  ],
  NON_COMPLIANT: [
    "WAITING_FOR_CORRECTION",
    "COMPLIANT",
    "CLEARED",
    "HUMAN_REVIEW",
    "BLOCKED",
    "CLOSED",
  ],
  WAITING_FOR_CORRECTION: [
    "DOCUMENT_RECEIVED",
    "BLOCKED",
    "HUMAN_REVIEW",
    "CLOSED",
  ],
  UNDER_REVIEW: ["COMPLIANT", "HUMAN_REVIEW", "BLOCKED", "CLOSED"],
  COMPLIANT: ["CLEARED", "HUMAN_REVIEW", "CLOSED"],
  CLEARED: ["CLOSED"],
  BLOCKED: ["CLOSED"],
  HUMAN_REVIEW: ["COMPLIANT", "CLEARED", "BLOCKED", "CLOSED"],
  CLOSED: [],
};

export type EventActor = "SYSTEM" | "USER" | "AGENT" | "BROKER" | "VENDOR";
